# Uncomment the next line to define a global platform for your project
 platform :ios, '9.0'

target 'Benefit' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for Benefit

  pod 'Spring', :git => 'https://github.com/MengTo/Spring.git'
  pod 'ImageSlideshow', '~> 1.4'
  pod 'MIBadgeButton-Swift', :git => 'https://github.com/mustafaibrahim989/MIBadgeButton-Swift.git', :branch => 'master'
  pod 'Charts'
  pod 'SideMenu'
  pod 'JTHamburgerButton', '~> 1.0'
  pod 'SwiftyJSON'
  pod 'Alamofire'
  pod 'Google/SignIn'

end
